import { BUILDERS, MethodRegistry, PROPERTY_ALLOWLIST } from './registry';
import { queueInit, attachReady } from '../loop/init';
import { Nexus, NexusT } from './nexus';
import { bumpRenderableVersion } from './renderable-version';

/**
 * Registry mapping raw component objects to their Proxy wrappers.
 * This solves the JavaScript limitation where Proxy wrappers are lost
 * when stored as object properties (like component.parent).
 *
 * Using WeakMap ensures:
 * - No memory leaks (entries are GC'd when components are disposed)
 * - Fast O(1) lookup
 * - Components can be used as keys
 */
const PROXY_REGISTRY = new WeakMap<ComponentData, ComponentData>();

/**
 * Pre-computed lookup maps for nexus shorthand property access.
 * Maps both kebab-case and camelCase forms to COMPONENT_TYPE strings.
 *
 * SINGULAR_TYPE_MAP: nexus.transform / nexus['cell-map'] → getComponentByType
 * PLURAL_TYPE_MAP:   nexus.sprites / nexus['cell-maps']  → getComponentsByType
 */
const SINGULAR_TYPE_MAP = new Map<string, string>();
const PLURAL_TYPE_MAP = new Map<string, string>();

// Populated after BUILDERS is available (deferred to first wrapInProxy call)
let nexusMapsBuilt = false;
function ensureNexusMaps(): void {
  if (nexusMapsBuilt) return;
  nexusMapsBuilt = true;

  for (const type of Object.keys(BUILDERS)) {
    // Kebab-case entry (e.g. 'cell-map')
    SINGULAR_TYPE_MAP.set(type, type);

    // CamelCase entry (e.g. 'cellMap')
    const camel = type.replace(/-([a-z])/g, (_, ch: string) =>
      ch.toUpperCase(),
    );
    if (camel !== type) {
      SINGULAR_TYPE_MAP.set(camel, type);
    }

    // Plurals: append 'es' for strings ending in s/x/z/sh/ch, otherwise 's'
    const needsEs = /(?:s|x|z|sh|ch)$/.test(type);
    PLURAL_TYPE_MAP.set(type + (needsEs ? 'es' : 's'), type);
    if (camel !== type) {
      PLURAL_TYPE_MAP.set(camel + (needsEs ? 'es' : 's'), type);
    }
  }
}

/**
 * Gets the Proxy wrapper for a component.
 *
 * This function is needed because when components store references to other
 * components (like parent), the Proxy wrapper is lost and only the raw target
 * object remains. This function retrieves the original Proxy wrapper.
 *
 * @param component - The component (may be raw or already proxied)
 * @returns The proxied version of the component
 *
 * @example
 * ```typescript
 * // In camera init:
 * const parentNexus = castTo<NexusT>(camera.parent!);
 * const viewport = parentNexus.getComponentByName('My Viewport', false);
 * ```
 */
export function castTo<T>(component: ComponentData): T {
  // Look up in registry - if not found, component might already be a Proxy or never registered
  const proxy = PROXY_REGISTRY.get(component);
  return (proxy || component) as T;
}

let COMPONENT_COUNT = 0;

/**
 * Resets the component ID counter.
 * Used when loading serialized scenes to ensure predictable IDs.
 */
export function resetComponentCount(): void {
  COMPONENT_COUNT = 0;
}

/**
 * Sets the component ID counter to a specific value.
 * Used after deserialization to continue ID generation from the highest deserialized ID.
 *
 * @param count - The new counter value
 */
export function setComponentCount(count: number): void {
  COMPONENT_COUNT = count;
}

/**
 * Defines the uniqueness constraints for components.
 *
 * - FALSE (0): Multiple instances allowed per Nexus
 * - LOCAL (1): Only one instance per parent Nexus (replaces boolean true)
 * - GLOBAL (2): Only one instance per entire scene hierarchy
 */
export enum ComponentUnique {
  FALSE = 0,
  LOCAL = 1,
  GLOBAL = 2,
  NAME = 3,
}

export type COMPONENT_TYPE =
  | 'nexus'
  | 'ui-overlay'
  | 'data-layer'
  | 'flag-manager'
  | 'fog-of-war'
  | 'messenger'
  | 'viewport'
  | 'texture-map'
  | 'atlas-manager'
  | 'sprite'
  | 'transform'
  | 'animation-controller'
  | 'animation-map'
  | 'cell-map'
  | 'camera'
  | 'input-controller'
  | 'collider'
  | 'event-collider'
  | 'timer'
  | 'speed-dial'
  | 'light'
  | 'vision-source'
  | 'audio-track'
  | 'audio-effect'
  | 'audio-player';

export interface ComponentOptions {
  name: string;
  overrideKey?: string;
  updateOverride?: string;
  initOverride?: string;
}

export interface ComponentData {
  name: string;
  type: COMPONENT_TYPE;
  id?: number;
  parent: ComponentData | null;
  _disposed?: boolean;
  loader?: boolean;
  /**
   * Transient marker: this component was generated by another component's loader
   * (e.g. the sprites/controller/texture-maps an `aseprite` component builds on
   * init). Such children are skipped by scene serialization — the owning loader
   * regenerates them on init — so the scene saves only the source declaration.
   * Not serialized.
   */
  _generated?: boolean;
  unique?: ComponentUnique;
  overrideKey?: string;
  updateOverride?: string;
  initOverride?: string;
  _initialized?: boolean;
  _initDefer?: number;
  ready?: Promise<boolean>;
  /**
   * Internal traversal optimization: whether this component, or (for a nexus)
   * anything in its subtree, has update-dispatchable work (a registered
   * `update()` on its type, or an instance `updateOverride`). `undefined`
   * means "not yet computed" and is treated as `true` (walk it) everywhere
   * this is consulted -- only an explicit `false` skips traversal. See
   * `computeOwnUpdateWork`/`bubbleUpdateWorkTrue`/`recomputeAndBubbleUpdateWork`
   * below and `traverseAndUpdate` in `src/loop/update.ts`.
   */
  _hasUpdateWork?: boolean;
}

export interface ComponentMethods {
  type: COMPONENT_TYPE;
  dispose?: (component: ComponentData) => void;
  update?: (component: ComponentData, deltaTime: number) => void;
  init?: (component: ComponentData) => Promise<void>;
  /**
   * Resumable initialization for components whose init is too heavy to run in a
   * single frame (e.g. atlas compilation). The progressive-init scheduler
   * advances the generator within the per-frame time budget and resumes it on
   * the next frame, so the game loop keeps rendering (loading UI stays live).
   * `yield` between work batches. Takes precedence over `init` when present.
   */
  initProgressive?: (component: ComponentData) => AsyncGenerator<void>;
}

/**
 * Converts a component methods interface into instance method signatures.
 * Removes the first parameter (the component itself) from each method,
 * transforming static methods into instance methods for TypeScript typing.
 *
 * This enables full IDE autocomplete and type safety for component method calls
 * (e.g., `nexus.addComponent()`) while maintaining the DOD architecture where
 * methods are stored centrally and dispatched via Proxy at runtime.
 *
 * @example
 * ```typescript
 * // Input: addComponent: (n: nexus, component: ComponentData) => void
 * // Output: addComponent: (component: ComponentData) => void
 * ```
 */
export type ComponentInstanceMethods<T extends ComponentMethods> = {
  [K in keyof T as K extends 'type' ? never : K]: T[K] extends (
    first: infer _First,
    ...args: infer Args
  ) => infer Return
    ? (...args: Args) => Return
    : never;
};

/**
 * Whether `component`'s own type/instance can ever have update-pass work
 * dispatched to it -- a registered `update()` on its type, or an instance
 * `updateOverride`. Ignores children (see `computeAggregateUpdateWork` for
 * the nexus-subtree version).
 */
function computeOwnUpdateWork(component: ComponentData): boolean {
  return !!MethodRegistry[component.type]?.update || !!component.updateOverride;
}

/**
 * `component`'s own update work OR'd with all its children's current
 * `_hasUpdateWork` (non-nexus components have no children, so this reduces
 * to `computeOwnUpdateWork`). A child counts as "has work" unless explicitly
 * known `false` -- same conservative default as the field itself.
 */
function computeAggregateUpdateWork(component: ComponentData): boolean {
  if (computeOwnUpdateWork(component)) return true;
  if (component.type !== 'nexus') return false;
  const { components } = component as ComponentData & {
    components?: ComponentData[];
  };
  return !!components?.some((c) => c._hasUpdateWork !== false);
}

/**
 * Walks from `component` up through `.parent`, setting `_hasUpdateWork = true`
 * and continuing -- stopping as soon as an ancestor is already `true` (by
 * invariant, everything further up is already correctly `true` too).
 */
export function bubbleUpdateWorkTrue(component: ComponentData): void {
  let current: ComponentData | null = component;
  while (current && current._hasUpdateWork !== true) {
    current._hasUpdateWork = true;
    current = current.parent;
  }
}

/**
 * Walks from `component` up through `.parent`, recomputing the aggregate at
 * each level and stopping as soon as a level's recomputed value matches its
 * current stored value (nothing changed, so nothing further up can have
 * changed either). Used when work could have been REMOVED (an aggregate can
 * only safely be blindly forced upward when work is being ADDED -- see
 * `bubbleUpdateWorkTrue`).
 */
function recomputeAndBubbleUpdateWork(component: ComponentData): void {
  let current: ComponentData | null = component;
  while (current) {
    const next = computeAggregateUpdateWork(current);
    if (current._hasUpdateWork === next) break;
    current._hasUpdateWork = next;
    current = current.parent;
  }
}

/**
 * Wraps a raw component object in a Proxy that enables method dispatch
 * via MethodRegistry and property access control via PROPERTY_ALLOWLIST.
 * Registers the proxy in PROXY_REGISTRY for later retrieval via castTo().
 *
 * @param component - Raw component data object (from builder or deserializer)
 * @returns Proxy-wrapped component
 */
/**
 * Base ComponentData properties, readable through the proxy on every
 * component type.
 */
const BASE_PROPERTIES: readonly string[] = [
  'name',
  'type',
  'id',
  'parent',
  '_disposed',
  'loader',
  '_generated',
  'unique',
  'overrideKey',
  'updateOverride',
  'initOverride',
  '_initialized',
  '_initDefer',
  'ready',
  '_hasUpdateWork',
];

/**
 * `BASE_PROPERTIES` unioned with a type's own allowlist, keyed on the
 * allowlist array itself. `PROPERTY_ALLOWLIST[type]` is written once per type
 * (at module load, or by `registerComponentType`, which refuses to overwrite
 * an existing type) and never mutated, so this is stable -- and keying on
 * identity rather than on the type name means a replaced array can't be
 * served a stale set.
 */
const allowedPropertyCache = new WeakMap<readonly string[], Set<string>>();

function allowedPropertiesFor(type: COMPONENT_TYPE): Set<string> {
  const allowlist = PROPERTY_ALLOWLIST[type] || [];
  let allowed = allowedPropertyCache.get(allowlist);
  if (allowed === undefined) {
    allowed = new Set(BASE_PROPERTIES);
    for (let i = 0; i < allowlist.length; i++) allowed.add(allowlist[i]);
    allowedPropertyCache.set(allowlist, allowed);
  }
  return allowed;
}

export function wrapInProxy(component: ComponentData): ComponentData {
  ensureNexusMaps();
  // A Set rather than an array for the same reason as `allowedProperties`
  // below, but snapshotted PER PROXY, not cached per type: `Object.keys` of
  // the method registry is already a point-in-time snapshot here, and a
  // proxy built before a later `registerMethod` has never seen the added key.
  // Caching by type would quietly change that.
  const proxyKeys = new Set(Object.keys(MethodRegistry[component.type]));

  // Computed here (not in newComponent/loader.ts) so every construction path
  // that wraps a component gets this for free -- both newComponent and scene
  // deserialization already set `updateOverride` on the raw object before
  // calling this function.
  component._hasUpdateWork = computeOwnUpdateWork(component);

  // Every allowed property for this type: the base ComponentData fields plus
  // the type's own allowlist, as ONE set. The `get` trap runs on every single
  // property read in the engine, so this used to be two linear `Array.includes`
  // scans -- reading a sprite's `_fowStatus` (last in its allowlist) cost ~32
  // string comparisons. Cached per allowlist ARRAY IDENTITY rather than per
  // type name, so it needs no invalidation hook: a type whose allowlist array
  // is ever replaced simply misses and rebuilds.
  const allowedProperties = allowedPropertiesFor(component.type);

  // Per-proxy cache of method wrappers, so repeated `component.method()` calls
  // reuse a single closure instead of allocating a new one on every access.
  const methodWrappers = new Map<string, (...args: unknown[]) => unknown>();

  const handler = {
    get: function (c: ComponentData, prop: string) {
      // Handle Promise detection (JavaScript checks for .then when awaiting)
      if (prop === 'then' || prop === 'catch' || prop === 'finally') {
        return undefined;
      }

      // Check if property is allowed (base or component-specific)
      if (allowedProperties.has(prop)) {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-expect-error
        return c[prop];
      }

      // Check if it's a method
      if (proxyKeys.has(prop)) {
        // Return a cached wrapper so repeated calls to the same method don't
        // allocate a fresh closure on every property access. The wrapper reads
        // MethodRegistry at call time, so re-registered method bodies are still
        // picked up.
        let wrapper = methodWrappers.get(prop);
        if (wrapper === undefined) {
          wrapper = (...args: unknown[]) => {
            // eslint-disable-next-line @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-call
            return MethodRegistry[component.type][prop](component, ...args);
          };
          methodWrappers.set(prop, wrapper);
        }
        return wrapper;
      }

      // Nexus shorthand: resolve child components by type or name
      if (c.type === 'nexus') {
        const singularType = SINGULAR_TYPE_MAP.get(prop);
        if (singularType) {
          // eslint-disable-next-line @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-call
          return MethodRegistry['nexus']['getComponentByType'](c, singularType);
        }
        const pluralType = PLURAL_TYPE_MAP.get(prop);
        if (pluralType) {
          // eslint-disable-next-line @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-call
          return MethodRegistry['nexus']['getComponentsByType'](c, pluralType);
        }
        // Name-based fallback
        // eslint-disable-next-line @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-call
        return MethodRegistry['nexus']['getComponentByName'](c, prop);
      }

      console.error(
        `${c.type} has no method named ${prop}. Available methods: ${[...proxyKeys].join(', ')}`,
      );
      // return do nothing func for graceful failure
      return () => {};
    },
    // Every other property write already falls through to the target
    // unchanged (no `set` trap existed before this one) -- that behavior is
    // preserved exactly below. `updateOverride` is the one property that
    // also needs to keep `_hasUpdateWork` correct on write, since it can
    // flip a component from "structurally has no update-pass work" to
    // "has work" (or back) after construction, not just at construction
    // time (which `wrapInProxy`'s own initial computation already covers).
    set: function (c: ComponentData, prop: string, value: unknown): boolean {
      if (prop === 'updateOverride') {
        const hadOverride = !!c.updateOverride;
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-expect-error
        c[prop] = value;
        const hasOverride = !!value;
        if (!hadOverride && hasOverride) {
          bubbleUpdateWorkTrue(c);
        } else if (hadOverride && !hasOverride) {
          recomputeAndBubbleUpdateWork(c);
        }
        // Overwriting one non-empty override with another doesn't change
        // presence, so no re-evaluation is needed.
        return true;
      }
      // `sprite.visible` writes (Sprite.setVisible(), and AnimationController's
      // direct sprite.visible = ... writes in init()/setLayerVisible()) all
      // flow through here -- one choke point instead of patching three call
      // sites. Bumping the version lets collect-renderables safely filter by
      // `visible` at collection time (see
      // 04-presentation-layer-visibility-skip/03-render-collection-visibility-split.md).
      // Guarded on an actual change so a no-op write (e.g. setVisible(true) on
      // an already-visible sprite) doesn't force every camera to re-walk.
      if (prop === 'visible' && c.type === 'sprite') {
        const changed =
          (c as unknown as { visible?: boolean }).visible !== value;
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-expect-error
        c[prop] = value;
        if (changed) bumpRenderableVersion('sprite');
        return true;
      }
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-expect-error
      c[prop] = value;
      return true;
    },
  };

  const proxy = new Proxy(component, handler);

  // Register the proxy in the registry so it can be retrieved later
  // This is crucial for components that store references to other components
  PROXY_REGISTRY.set(component, proxy);

  return proxy;
}

export async function newComponent(
  type: COMPONENT_TYPE,
  options: ComponentOptions,
  parent: NexusT | null = null,
  registerByName?: boolean,
): Promise<ComponentData | null> {
  const builder = BUILDERS[type];
  if (!builder) {
    console.error(
      `[NEW COMPONENT ERROR] component type ${type} does not exist`,
    );
    return null;
  }
  const component = (await builder(options)) as ComponentData;
  if (!component) {
    console.error(
      `[NEW COMPONENT ERROR] component named ${options.name} failed to build`,
    );
    return null;
  }
  component.id = COMPONENT_COUNT++;

  // Attach an awaitable `ready` promise before queuing init, so callers can
  // `await component.ready` even though init runs frame-budgeted on a later frame.
  attachReady(component);

  // Preserve ComponentData base fields from options
  if (options.overrideKey !== undefined) {
    component.overrideKey = options.overrideKey;
  }
  if (options.updateOverride !== undefined) {
    component.updateOverride = options.updateOverride;
  }
  if (options.initOverride !== undefined) {
    component.initOverride = options.initOverride;
  }

  // Automatically queue for initialization
  queueInit(component.id);

  const proxy = wrapInProxy(component);
  if (parent) {
    Nexus.addComponent(parent, proxy, registerByName);
  }

  return proxy;
}

// Type alias for serialized component data
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type SerializedData = Record<string, any>;

/**
 * Structured problem encountered during deserialization.
 *
 * Deserializers collect these rather than throwing so that the caller can
 * inspect every issue in one pass. A non-empty errors array does not
 * necessarily mean the component is null — malformed nested data (bad
 * vectors, missing optional fields) is recorded here while the component
 * is still reconstructed using sensible defaults.
 */
export interface DeserializationError {
  /** Machine-readable category, e.g. 'TYPE_MISMATCH', 'MISSING_NAME', 'INVALID_VECTOR'. */
  code: string;
  /** Human-readable description. */
  message: string;
  /**
   * Occurrence count. Defaults to 1 when undefined. Used by texture-map's
   * tallying (where hundreds of identical per-frame errors collapse to one).
   */
  count?: number;
}

/**
 * Return shape for every component deserializer.
 *
 * `component` is null only when deserialization can't produce a usable
 * object — typically type mismatch or missing identity (`name`). For
 * recoverable issues, `component` is non-null and `errors` describes what
 * was coerced to defaults.
 */
export interface DeserializeResult<T = ComponentData> {
  component: T | null;
  errors: DeserializationError[];
}

export interface ComponentSerializer {
  serialize(component: ComponentData): SerializedData;
  deserialize(
    data: SerializedData,
  ):
    | DeserializeResult<ComponentData>
    | Promise<DeserializeResult<ComponentData>>;
}
