import { BUILDERS, MethodRegistry, PROPERTY_ALLOWLIST } from './registry';
import { queueInit, attachReady } from '../loop/init';
import { Nexus, NexusT } from './nexus';

/**
 * Registry mapping raw component objects to their Proxy wrappers.
 * This solves the JavaScript limitation where Proxy wrappers are lost
 * when stored as object properties (like component.parent).
 *
 * Using WeakMap ensures:
 * - No memory leaks (entries are GC'd when components are disposed)
 * - Fast O(1) lookup
 * - Components can be used as keys
 */
const PROXY_REGISTRY = new WeakMap<ComponentData, ComponentData>();

/**
 * Pre-computed lookup maps for nexus shorthand property access.
 * Maps both kebab-case and camelCase forms to COMPONENT_TYPE strings.
 *
 * SINGULAR_TYPE_MAP: nexus.transform / nexus['cell-map'] → getComponentByType
 * PLURAL_TYPE_MAP:   nexus.sprites / nexus['cell-maps']  → getComponentsByType
 */
const SINGULAR_TYPE_MAP = new Map<string, string>();
const PLURAL_TYPE_MAP = new Map<string, string>();

// Populated after BUILDERS is available (deferred to first wrapInProxy call)
let nexusMapsBuilt = false;
function ensureNexusMaps(): void {
  if (nexusMapsBuilt) return;
  nexusMapsBuilt = true;

  for (const type of Object.keys(BUILDERS)) {
    // Kebab-case entry (e.g. 'cell-map')
    SINGULAR_TYPE_MAP.set(type, type);

    // CamelCase entry (e.g. 'cellMap')
    const camel = type.replace(/-([a-z])/g, (_, ch: string) =>
      ch.toUpperCase(),
    );
    if (camel !== type) {
      SINGULAR_TYPE_MAP.set(camel, type);
    }

    // Plurals: append 'es' for strings ending in s/x/z/sh/ch, otherwise 's'
    const needsEs = /(?:s|x|z|sh|ch)$/.test(type);
    PLURAL_TYPE_MAP.set(type + (needsEs ? 'es' : 's'), type);
    if (camel !== type) {
      PLURAL_TYPE_MAP.set(camel + (needsEs ? 'es' : 's'), type);
    }
  }
}

/**
 * Gets the Proxy wrapper for a component.
 *
 * This function is needed because when components store references to other
 * components (like parent), the Proxy wrapper is lost and only the raw target
 * object remains. This function retrieves the original Proxy wrapper.
 *
 * @param component - The component (may be raw or already proxied)
 * @returns The proxied version of the component
 *
 * @example
 * ```typescript
 * // In camera init:
 * const parentNexus = castTo<NexusT>(camera.parent!);
 * const viewport = parentNexus.getComponentByName('My Viewport', false);
 * ```
 */
export function castTo<T>(component: ComponentData): T {
  // Look up in registry - if not found, component might already be a Proxy or never registered
  const proxy = PROXY_REGISTRY.get(component);
  return (proxy || component) as T;
}

let COMPONENT_COUNT = 0;

/**
 * Resets the component ID counter.
 * Used when loading serialized scenes to ensure predictable IDs.
 */
export function resetComponentCount(): void {
  COMPONENT_COUNT = 0;
}

/**
 * Sets the component ID counter to a specific value.
 * Used after deserialization to continue ID generation from the highest deserialized ID.
 *
 * @param count - The new counter value
 */
export function setComponentCount(count: number): void {
  COMPONENT_COUNT = count;
}

/**
 * Defines the uniqueness constraints for components.
 *
 * - FALSE (0): Multiple instances allowed per Nexus
 * - LOCAL (1): Only one instance per parent Nexus (replaces boolean true)
 * - GLOBAL (2): Only one instance per entire scene hierarchy
 */
export enum ComponentUnique {
  FALSE = 0,
  LOCAL = 1,
  GLOBAL = 2,
  NAME = 3,
}

export type COMPONENT_TYPE =
  | 'nexus'
  | 'ui-overlay'
  | 'data-layer'
  | 'flag-manager'
  | 'messenger'
  | 'viewport'
  | 'texture-map'
  | 'atlas-manager'
  | 'sprite'
  | 'transform'
  | 'animation-controller'
  | 'cell-map'
  | 'camera'
  | 'input-controller'
  | 'collider'
  | 'event-collider'
  | 'timer'
  | 'speed-dial'
  | 'light'
  | 'audio-track'
  | 'audio-effect'
  | 'audio-player';

export interface ComponentOptions {
  name: string;
  overrideKey?: string;
  updateOverride?: string;
  initOverride?: string;
}

export interface ComponentData {
  name: string;
  type: COMPONENT_TYPE;
  id?: number;
  parent: ComponentData | null;
  _disposed?: boolean;
  loader?: boolean;
  /**
   * Transient marker: this component was generated by another component's loader
   * (e.g. the sprites/controller/texture-maps an `aseprite` component builds on
   * init). Such children are skipped by scene serialization — the owning loader
   * regenerates them on init — so the scene saves only the source declaration.
   * Not serialized.
   */
  _generated?: boolean;
  unique?: ComponentUnique;
  overrideKey?: string;
  updateOverride?: string;
  initOverride?: string;
  _initialized?: boolean;
  _initDefer?: number;
  ready?: Promise<boolean>;
}

export interface ComponentMethods {
  type: COMPONENT_TYPE;
  dispose?: (component: ComponentData) => void;
  update?: (component: ComponentData, deltaTime: number) => void;
  init?: (component: ComponentData) => Promise<void>;
  /**
   * Resumable initialization for components whose init is too heavy to run in a
   * single frame (e.g. atlas compilation). The progressive-init scheduler
   * advances the generator within the per-frame time budget and resumes it on
   * the next frame, so the game loop keeps rendering (loading UI stays live).
   * `yield` between work batches. Takes precedence over `init` when present.
   */
  initProgressive?: (component: ComponentData) => AsyncGenerator<void>;
}

/**
 * Converts a component methods interface into instance method signatures.
 * Removes the first parameter (the component itself) from each method,
 * transforming static methods into instance methods for TypeScript typing.
 *
 * This enables full IDE autocomplete and type safety for component method calls
 * (e.g., `nexus.addComponent()`) while maintaining the DOD architecture where
 * methods are stored centrally and dispatched via Proxy at runtime.
 *
 * @example
 * ```typescript
 * // Input: addComponent: (n: nexus, component: ComponentData) => void
 * // Output: addComponent: (component: ComponentData) => void
 * ```
 */
export type ComponentInstanceMethods<T extends ComponentMethods> = {
  [K in keyof T as K extends 'type' ? never : K]: T[K] extends (
    first: infer _First,
    ...args: infer Args
  ) => infer Return
    ? (...args: Args) => Return
    : never;
};

/**
 * Wraps a raw component object in a Proxy that enables method dispatch
 * via MethodRegistry and property access control via PROPERTY_ALLOWLIST.
 * Registers the proxy in PROXY_REGISTRY for later retrieval via castTo().
 *
 * @param component - Raw component data object (from builder or deserializer)
 * @returns Proxy-wrapped component
 */
export function wrapInProxy(component: ComponentData): ComponentData {
  ensureNexusMaps();
  const proxyKeys = Object.keys(MethodRegistry[component.type]);

  // Base ComponentData properties (always allowed)
  const baseProperties = [
    'name',
    'type',
    'id',
    'parent',
    '_disposed',
    'loader',
    '_generated',
    'unique',
    'overrideKey',
    'updateOverride',
    'initOverride',
    '_initialized',
    '_initDefer',
    'ready',
  ];

  // Component-specific properties
  const componentAllowlist = PROPERTY_ALLOWLIST[component.type] || [];

  // Per-proxy cache of method wrappers, so repeated `component.method()` calls
  // reuse a single closure instead of allocating a new one on every access.
  const methodWrappers = new Map<string, (...args: unknown[]) => unknown>();

  const handler = {
    get: function (c: ComponentData, prop: string) {
      // Handle Promise detection (JavaScript checks for .then when awaiting)
      if (prop === 'then' || prop === 'catch' || prop === 'finally') {
        return undefined;
      }

      // Check if property is allowed (base or component-specific)
      if (baseProperties.includes(prop) || componentAllowlist.includes(prop)) {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-expect-error
        return c[prop];
      }

      // Check if it's a method
      if (proxyKeys.indexOf(prop) !== -1) {
        // Return a cached wrapper so repeated calls to the same method don't
        // allocate a fresh closure on every property access. The wrapper reads
        // MethodRegistry at call time, so re-registered method bodies are still
        // picked up.
        let wrapper = methodWrappers.get(prop);
        if (wrapper === undefined) {
          wrapper = (...args: unknown[]) => {
            // eslint-disable-next-line @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-call
            return MethodRegistry[component.type][prop](component, ...args);
          };
          methodWrappers.set(prop, wrapper);
        }
        return wrapper;
      }

      // Nexus shorthand: resolve child components by type or name
      if (c.type === 'nexus') {
        const singularType = SINGULAR_TYPE_MAP.get(prop);
        if (singularType) {
          // eslint-disable-next-line @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-call
          return MethodRegistry['nexus']['getComponentByType'](c, singularType);
        }
        const pluralType = PLURAL_TYPE_MAP.get(prop);
        if (pluralType) {
          // eslint-disable-next-line @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-call
          return MethodRegistry['nexus']['getComponentsByType'](c, pluralType);
        }
        // Name-based fallback
        // eslint-disable-next-line @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-call
        return MethodRegistry['nexus']['getComponentByName'](c, prop);
      }

      console.error(
        `${c.type} has no method named ${prop}. Available methods: ${proxyKeys.join(', ')}`,
      );
      // return do nothing func for graceful failure
      return () => {};
    },
  };

  const proxy = new Proxy(component, handler);

  // Register the proxy in the registry so it can be retrieved later
  // This is crucial for components that store references to other components
  PROXY_REGISTRY.set(component, proxy);

  return proxy;
}

export async function newComponent(
  type: COMPONENT_TYPE,
  options: ComponentOptions,
  parent: NexusT | null = null,
): Promise<ComponentData | null> {
  const builder = BUILDERS[type];
  if (!builder) {
    console.error(
      `[NEW COMPONENT ERROR] component type ${type} does not exist`,
    );
    return null;
  }
  const component = (await builder(options)) as ComponentData;
  if (!component) {
    console.error(
      `[NEW COMPONENT ERROR] component named ${options.name} failed to build`,
    );
    return null;
  }
  component.id = COMPONENT_COUNT++;

  // Attach an awaitable `ready` promise before queuing init, so callers can
  // `await component.ready` even though init runs frame-budgeted on a later frame.
  attachReady(component);

  // Preserve ComponentData base fields from options
  if (options.overrideKey !== undefined) {
    component.overrideKey = options.overrideKey;
  }
  if (options.updateOverride !== undefined) {
    component.updateOverride = options.updateOverride;
  }
  if (options.initOverride !== undefined) {
    component.initOverride = options.initOverride;
  }

  // Automatically queue for initialization
  queueInit(component.id);

  const proxy = wrapInProxy(component);
  if (parent) {
    Nexus.addComponent(parent, proxy);
  }

  return proxy;
}

// Type alias for serialized component data
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type SerializedData = Record<string, any>;

/**
 * Structured problem encountered during deserialization.
 *
 * Deserializers collect these rather than throwing so that the caller can
 * inspect every issue in one pass. A non-empty errors array does not
 * necessarily mean the component is null — malformed nested data (bad
 * vectors, missing optional fields) is recorded here while the component
 * is still reconstructed using sensible defaults.
 */
export interface DeserializationError {
  /** Machine-readable category, e.g. 'TYPE_MISMATCH', 'MISSING_NAME', 'INVALID_VECTOR'. */
  code: string;
  /** Human-readable description. */
  message: string;
  /**
   * Occurrence count. Defaults to 1 when undefined. Used by texture-map's
   * tallying (where hundreds of identical per-frame errors collapse to one).
   */
  count?: number;
}

/**
 * Return shape for every component deserializer.
 *
 * `component` is null only when deserialization can't produce a usable
 * object — typically type mismatch or missing identity (`name`). For
 * recoverable issues, `component` is non-null and `errors` describes what
 * was coerced to defaults.
 */
export interface DeserializeResult<T = ComponentData> {
  component: T | null;
  errors: DeserializationError[];
}

export interface ComponentSerializer {
  serialize(component: ComponentData): SerializedData;
  deserialize(
    data: SerializedData,
  ):
    | DeserializeResult<ComponentData>
    | Promise<DeserializeResult<ComponentData>>;
}
